### ISSUE TITLE
"warning labels and messages" style rules overridden

### ISSUE THREAD

**Issue by jensschuppe** [civicrm/org.civicrm.shoreditch#242]
The highlighting of overdue or scheduled activities is gone due to more specific rules within the shoreditch stylesheet, e.g. in
```CSS
.page-civicrm-contact #mainTabContainer .crm-activity-selector-activity div[id*="DataTables_Table_"] table.dataTable>tbody>tr>td {
    /* ... */
    color: #4D4D69;
    /* ... */
}
```
This is the original style declaration with the color highlighting:
```CSS
.crm-container del, .crm-container .crm-is_deleted, .crm-container table.caseSelector td.status-urgent, .crm-container .font-red, .crm-container .status-removed, .crm-container .status-overdue, .crm-container .status-fatal, .crm-container .status-hold, .crm-container .status-past, .crm-contact-deceased, .crm-container .status-warning {
    color: #E43D2B !important;
}
```
This should be extended to include subsequent elements as well, so that they are only overridden if there is a more specific rule:
```CSS
.crm-container del *,
.crm-container .crm-is_deleted *,
.crm-container table.caseSelector td.status-urgent *,
.crm-container .font-red *,
.crm-container .status-removed *,
.crm-container .status-overdue *,
.crm-container .status-fatal *,
.crm-container .status-hold *,
.crm-container .status-past *,
.crm-contact-deceased *,
.crm-container .status-warning * {
  color: #E43D2B;
}
```
Note the missing `!important` so that deliberately overriding is still possible.

Also, this is not tested in scenarios other than the activity list.

I just inspected the generated CSS, so unfortunately I can't provide a patch for the SCSS.
