### ISSUE TITLE
Membership Date not completely visible on contact summary page.

### ISSUE THREAD

**Issue by jitendrapurohit** [civicrm/org.civicrm.shoreditch#428]
Visit any contact having a membership dates set in December(or any month with a long name)

The date fields displayed are not wide enough to show the year in the 3 date fields

![image](https://user-images.githubusercontent.com/5929648/70596390-cabfb200-1c0b-11ea-9825-33853dc37eec.png)

Possibly because the membership dates specify a hardcode `max-width` to these columns?  See https://github.com/civicrm/org.civicrm.shoreditch/blob/master/scss/civicrm/contact/pages/_memberships.scss#L24

```css
  #memberships {
    @include civicrm-table-with-header();

    table td {
      &:not(:last-child) {
        max-width: 85px;
        overflow: hidden;
        padding: 15px 10px 15px 20px;
        text-overflow: ellipsis;
        white-space: nowrap;
      }

      &:nth-child(2),
      &:nth-child(3),
      &:nth-child(4) {
        max-width: 100px;
      }
    }
  }
```
